version: "3.8"

services:
  mariadb:
    image: mediafile_mariadb:latest
    container_name: mariadb
    restart: always
    environment:
      - MARIADB_ROOT_PASSWORD=${MARIA_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql:rw,delegated
    ports:
      - "3306:3306"
    networks:
      auth_net:
        ipv4_address: 172.20.0.10

  app:
    image: diegomated1/mediafile-authentication-service:${APP_VERSION}
    container_name: auth_service
    restart: always
    depends_on: [mariadb]
    environment:
      - HOST=10.154.12.162
      - PORT=3000
      - MARIA_CONNECTION_STRING=jdbc:mariadb://172.20.0.10:3306/Auth
      - MARIA_USER=root
      - MARIA_PASSWORD=${MARIA_PASSWORD}
      - JAVA_OPTS=-Djava.rmi.server.hostname=10.154.12.162
    network_mode: "host"

networks:
  auth_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
          gateway: 172.20.0.1

volumes:
  db_data: